[workspace]
members = ["graph_core", "graph_cli", "graph_py", "graph_api"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
authors = ["paullj <paullj1998@gmail.com.org>"]
repository = ""
license = "MIT"
