name: api

on:
  push:
    branches:
      - main
    paths:
      - "graph_core/**"
      - "graph_api/**"
      - "Cargot.toml"
      - "Cargot.lock"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
