name: app
on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Node.js version from .tool-versions file
        id: node-version
        run: echo "::set-output name=version::$(grep nodejs .tool-versions | cut -f 2 -d ' ')"

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.version }}

      - name: Extract pnpm version from .tool-versions file
        id: pnpm-version
        run: echo "::set-output name=version::$(grep pnpm .tool-versions | cut -f 2 -d ' ')"

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        id: pnpm-install
        with:
          version: ${{ steps.pnpm-version.outputs.version }}
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
        working-directory: ./graph_app

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: pnpm build
        working-directory: ./graph_app

      - name: Release Artifcat
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
        working-directory: ./graph_app

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
